export const initialMemos = [
  {
    id: 'memo-1',
    title: '이것은 제목입니다',
    content: '오늘 해야 할 일을 정리하고 메모를 작성해 보세요.',
    category: 'daily',
    date: '2026-09-08',
    isPinned: true,
  },
  {
    id: 'memo-2',
    title: '이것은 제목입니다',
    content: '프로젝트에서 확인할 항목과 다음 작업을 기록합니다.',
    category: 'work',
    date: '2026-09-08',
    isPinned: true,
  },
  {
    id: 'memo-3',
    title: '이것은 제목입니다',
    content: '생각난 내용을 간단하게 기록해 둡니다.',
    category: 'others',
    date: '2026-09-07',
    isPinned: false,
  },
  {
    id: 'memo-4',
    title: '이것은 제목입니다',
    content: '오늘의 일정을 확인하고 필요한 일을 적어 둡니다.',
    category: 'daily',
    date: '2026-09-07',
    isPinned: false,
  },
  {
    id: 'memo-5',
    title: '이것은 제목입니다',
    content: '업무 중 놓치지 말아야 할 내용을 정리합니다.',
    category: 'work',
    date: '2026-09-06',
    isPinned: false,
  },
  {
    id: 'memo-6',
    title: '이것은 제목입니다',
    content: '나중에 다시 확인할 내용을 남겨 둡니다.',
    category: 'others',
    date: '2026-09-06',
    isPinned: false,
  },
];
